var specs = [
    {title: "HTML5", uri: "http://dev.w3.org/html5/spec/Overview.html"},
    {title: "HTML5 AppCache / Offline", uri: "http://dev.w3.org/html5/spec/Overview.html#offline"},
    {title: "HTML5 Drag and Drop", uri: "http://dev.w3.org/html5/spec/Overview.html#dnd"},
    {title: "HTML5 Forms", uri: "http://dev.w3.org/html5/spec/Overview.html#forms"},
    {title: "HTML5 audio element", uri: "http://dev.w3.org/html5/spec/Overview.html#audio"},
    {title: "HTML5 canvas element", uri: "http://dev.w3.org/html5/spec/Overview.html#the-canvas-element"},
    {title: "HTML5 meter element", uri: "http://dev.w3.org/html5/spec/Overview.html#the-meter-element"},
    {title: "HTML5 progress element", uri: "http://dev.w3.org/html5/spec/Overview.html#the-progress-element"},
    {title: "HTML5 video element", uri: "http://dev.w3.org/html5/spec/Overview.html#video"},
    {title: "HTML5+RDFA", uri: "http://dev.w3.org/html5/rdfa/"},
    {title: "HTML5 Microdata", uri: "http://dev.w3.org/html5/md/"},
    {title: "HTML5 Canvas 2D Context", uri: "http://dev.w3.org/html5/2dcontext/"},
    {title: "CORS", uri: "http://dev.w3.org/2006/waf/access-control/"},
    {title: "DOM L3 Events", uri: "http://dev.w3.org/2006/webapi/DOM-Level-3-Events/html/DOM3-Events.html"},
    {title: "Element Traversal", uri: "http://www.w3.org/TR/ElementTraversal/"},
    {title: "File API", uri: "http://dev.w3.org/2006/webapi/FileAPI/"},
    {title: "File API: Directories and System", uri: "http://dev.w3.org/2009/dap/file-system/file-dir-sys.html"},
    {title: "File API: Writer", uri: "http://dev.w3.org/2009/dap/file-system/file-writer.html"},
    {title: "Indexed Database API", uri: "http://dvcs.w3.org/hg/IndexedDB/raw-file/tip/Overview.html"},
    {title: "Progress Events", uri: "http://dev.w3.org/2006/webapi/progress/Progress.html"},
    {title: "Selectors API", uri: "http://dev.w3.org/2006/webapi/selectors-api/"},
    {title: "Server-sent Events", uri: "http://dev.w3.org/html5/eventsource/"},
    {title: "DOM Core", uri: "http://dvcs.w3.org/hg/domcore/raw-file/tip/Overview.html"},
    {title: "Web Messaging", uri: "http://dev.w3.org/html5/postmsg/"},
    {title: "Web SQL Database", uri: "http://www.w3.org/TR/webdatabase/"},
    {title: "Web Sockets API", uri: "http://dev.w3.org/html5/websockets/"},
    {title: "Web Storage", uri: "http://dev.w3.org/html5/webstorage/"},
    {title: "Web Workers", uri: "http://dev.w3.org/html5/workers/"},
    {title: "XHR Level 1", uri: "http://dev.w3.org/2006/webapi/XMLHttpRequest/"},
    {title: "XHR Level 2", uri: "http://dev.w3.org/2006/webapi/XMLHttpRequest-2/"},
    {title: "CSS 2.1", uri: "http://www.w3.org/Style/CSS/specs#css21"},
    {title: "CSS Namespaces Level 3", uri: "http://dev.w3.org/csswg/css3-namespace/"},
    {title: "CSS Selectors Level 3", uri: "http://dev.w3.org/csswg/selectors3/"},
    {title: "CSS Media Queries", uri: "http://dev.w3.org/csswg/css3-mediaqueries/"},
    {title: "CSS3 2D Transformations", uri: "http://dev.w3.org/csswg/css3-2d-transforms/"},
    {title: "CSS3 3D Transformations", uri: "http://dev.w3.org/csswg/css3-3d-transforms/"},
    {title: "CSS3 Animations", uri: "http://dev.w3.org/csswg/css3-animations/"},
    {title: "CSS3 Backgrounds and Borders", uri: "http://dev.w3.org/csswg/css3-background/"},
    {title: "CSS3 Color", uri: "http://dev.w3.org/csswg/css3-color/"},
    {title: "CSS3 Flexible Box Layout", uri: "http://dev.w3.org/csswg/css3-flexbox"},
    {title: "CSS3 Fonts", uri: "http://dev.w3.org/csswg/css3-fonts/"},
    {title: "CSS3 Multi-column Layout", uri: "http://dev.w3.org/csswg/css3-multicol/"},
    {title: "CSS3 Text", uri: "http://dev.w3.org/csswg/css3-text/"},
    {title: "CSS3 Text: overflow", uri: "http://dev.w3.org/csswg/css3-text/#text-overflow"},
    {title: "CSS3 Text: shadow", uri: "http://dev.w3.org/csswg/css3-text/#text-shadow"},
    {title: "CSS3 Text: wrap", uri: "http://dev.w3.org/csswg/css3-text/#text-wrap"},
    {title: "CSS3 Transitions", uri: "http://dev.w3.org/csswg/css3-transitions/"},
    {title: "CSS3 User Interface", uri: "http://dev.w3.org/csswg/css3-ui"},
    {title: "CSS3 Values and Units", uri: "http://dev.w3.org/csswg/css3-values"},
    {title: "CSSOM", uri: "http://dev.w3.org/csswg/cssom/"},
    {title: "CSSOM View", uri: "http://dev.w3.org/csswg/cssom-view/"},
    {title: "DeviceOrientation, Accelerometer", uri: "http://dev.w3.org/geo/api/spec-source-orientation.html"},
    {title: "Geolocation API", uri: "http://dev.w3.org/geo/api/spec-source.html"},
    {title: "Contacts API", uri: "http://dev.w3.org/2009/dap/contacts/"},
    {title: "HTML Media Capture", uri: "http://dev.w3.org/2009/dap/camera/"},
    {title: "SVG 1.1", uri: "http://www.w3.org/TR/SVG11/"},
    {title: "WebGL", uri: "https://cvs.khronos.org/svn/repos/registry/trunk/public/webgl/doc/spec/WebGL-spec.html"},
    {title: "WAI ARIA", uri: "http://www.w3.org/TR/wai-aria/"},{title: "MathML v2", uri: "http://www.w3.org/TR/MathML2/"},
    {title: "Media Fragments URI", uri: "http://www.w3.org/2008/WebVideo/Fragments/WD-media-fragments-spec/"},
    {title: "Navigation Timing", uri: "http://www.w3.org/TR/navigation-timing/"},
    {title: "Web Notifications", uri: "http://dev.w3.org/2006/webapi/WebNotifications/publish/Notifications.html"},
    {title: "WOFF", uri: "http://www.w3.org/TR/WOFF"},
    {title: "Resource Timing", uri: "http://dvcs.w3.org/hg/webperf/raw-file/tip/specs/ResourceTiming/Overview.html"},
    {title: "User Timing", uri: "http://dvcs.w3.org/hg/webperf/raw-file/tip/specs/UserTiming/Overview.html"},
    {title: "Web URL Notifications", uri: "http://dev.w3.org/2006/webapi/WebNotifications/publish/WebNotifications.html"},
    {title: "Touch Events", uri: "http://dvcs.w3.org/hg/webevents/raw-file/tip/touchevents.html"},
    {title: "Battery Status", uri: "http://dvcs.w3.org/hg/dap/raw-file/tip/battery/Overview.html"},
    {title: "Vibration API", uri: "http://dev.w3.org/2009/dap/vibration/"},
    {title: "Proximity Events", uri: "http://dvcs.w3.org/hg/dap/raw-file/tip/proximity/Overview.html"}
];